# Generated by Django 4.2.7 on 2023-11-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('ano_publicacion', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('paginas', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('issn', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=100)),
                ('fecha_publi', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('NU', 'Nuevo'), ('US', 'Usado')], max_length=2)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=3, max_digits=100)),
                ('descuento', models.DecimalField(decimal_places=3, max_digits=100)),
                ('categoria', models.CharField(choices=[('LI', 'Libros'), ('RE', 'Revistas'), ('DI', 'Diccionarios'), ('EN', 'Enciclopedias'), ('NO', 'Novelas'), ('CO', 'Comics')], max_length=3)),
                ('imagen_producto', models.ImageField(upload_to='product')),
            ],
        ),
    ]
