# Generated by Django 4.2.7 on 2023-11-03 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.CharField(choices=[('Amazonas', 'Amazonas'), ('Antioquia', 'Antioquia'), ('Arauca', 'Arauca'), ('Atlantico', 'Atlantico'), ('Bogota', 'Bogota'), ('Bolívar', 'Bolívar'), ('Boyaca', 'Boyaca'), ('Caldas', 'Caldas'), ('Caqueta', 'Caqueta'), ('Casanare', 'Casanare'), ('Cauca', 'Cauca'), ('Cesar', 'Cesar'), ('Choco', 'Choco'), ('Cordoba', 'Cordoba'), ('Cundinamarca', 'Cundinamarca'), ('Guainia', 'Guainia'), ('Guaviare', 'Guaviare'), ('Huila', 'Huila'), ('Guajira', 'Guajira'), ('Magdalena', 'Magdalena'), ('Meta', 'Meta'), ('Nariño', 'Nariño'), ('Putumayo', 'Putumayo'), ('Norte de Santander', 'Norte de Santander'), ('Quindío', 'Quindío'), ('Risaralda', 'Risaralda'), ('San Andrés y Providencia', 'San Andrés y Providencia'), ('Santander', 'Santander'), ('Sucre\t', 'Sucre'), ('Tolima', 'Tolima'), ('Valle del Cauca', 'Valle del Cauca'), ('Vaupes', 'Vaupes'), ('Vichada', 'Vichada')], max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField(default=0)),
                ('codigo_postal', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
